FROM node:alpine as build

LABEL author="Jesse Zenon"
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/build /user/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]